### ISSUE TITLE
using Winston fails julia  0.3.0 x86_64-linux-gnu (Xubuntu 14.04 LTS)

### ISSUE THREAD

**Issue by bwharris1967** [nolta/Winston.jl#169]
# See below.  I tried installing the libglib2.0-dev package but it didn't help.  Any sugestions?

julia> Pkg.update()
INFO: Updating METADATA...
INFO: Updating cache of REPLCompletions...
INFO: Updating cache of IJulia...
INFO: Computing changes...
INFO: Upgrading Color: v0.3.3 => v0.3.4
INFO: Upgrading IJulia: v0.1.13 => v0.1.14
INFO: Upgrading Winston: v0.11.2 => v0.11.4
INFO: Building Nettle
INFO: Building ZMQ
INFO: Building IJulia
Found IPython version 1.2.1 ... ok.
Creating julia profile in IPython...
(Existing KernelManager.kernel_cmd setting in ipython_config.py is untouched.)
(Existing IPythonWidget.execute_on_complete_input setting in ipython_qtconsole_config.py is untouched.)
(Existing FrontendWidget.lexer_class setting in ipython_qtconsole_config.py is untouched.)
(Existing NotebookApp.port setting in ipython_notebook_config.py is untouched.)
(Existing ipynblogo.png file untouched.)
(Existing ipynblogo.svg file untouched.)
(Existing favicon.ico file untouched.)
(Existing custom.js file untouched.)
(Existing julia.js file untouched.)
INFO: Building Cairo
Installing dependency libglib2.0-0 via `sudo apt-get install libglib2.0-0`:
Reading package lists... Done
Building dependency tree  
Reading state information... Done
libglib2.0-0 is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
INFO: Building Tk

julia> using Winston
ERROR: _jl_libgobject not defined
 in init at /home/bharris/.julia/v0.3/Tk/src/tkwidget.jl:36
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:54
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:51
while loading /home/bharris/.julia/v0.3/Tk/src/tkwidget.jl, in expression stng on line 452
while loading /home/bharris/.julia/v0.3/Tk/src/Tk.jl, in expression startingline 25
while loading /home/bharris/.julia/v0.3/Winston/src/tk.jl, in expression stag on line 1
while loading /home/bharris/.julia/v0.3/Winston/src/Winston.jl, in expressioarting on line 2699

julia> quit()

**Comment by ararslan** [comment]
Closing as this package no longer supports Julia 0.3.
