### ISSUE TITLE
Can`t run Winston ERROR: LoadError: UndefVarError: Graphics not defined

### ISSUE THREAD

**Issue by paulanalyst** [nolta/Winston.jl#205]
Cant run Winston ERROR: LoadError: UndefVarError: Graphics not defined
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-dev+3600 (2015-02-25 15:26 UTC)
 _/ |\__'_|_|_|__'_|  |  Commit f96c23c\* (0 days old master)
|__/                   |  x86_64-w64-mingw32

julia> Pkg.status()
INFO: Initializing package repository C:\Users\SAMSUNG2.julia\v0.4
INFO: Cloning METADATA from git://github.com/JuliaLang/METADATA.jl
No packages installed

julia> Pkg.add("Winston")
INFO: Cloning cache of BinDeps from git://github.com/JuliaLang/BinDeps.jl.git
INFO: Cloning cache of Cairo from git://github.com/JuliaLang/Cairo.jl.git
INFO: Cloning cache of Color from git://github.com/JuliaLang/Color.jl.git
INFO: Cloning cache of Compat from git://github.com/JuliaLang/Compat.jl.git
INFO: Cloning cache of FixedPointNumbers from git://github.com/JeffBezanson/FixedPointNumbers.jl.git
INFO: Cloning cache of Graphics from git://github.com/JuliaLang/Graphics.jl.git
INFO: Cloning cache of IniFile from git://github.com/JuliaLang/IniFile.jl.git
INFO: Cloning cache of LibExpat from git://github.com/amitmurthy/LibExpat.jl.git
INFO: Cloning cache of SHA from git://github.com/staticfloat/SHA.jl.git
INFO: Cloning cache of Tk from git://github.com/JuliaLang/Tk.jl.git
INFO: Cloning cache of URIParser from git://github.com/JuliaWeb/URIParser.jl.git
INFO: Cloning cache of WinRPM from git://github.com/JuliaLang/WinRPM.jl.git
INFO: Cloning cache of Winston from git://github.com/nolta/Winston.jl.git
INFO: Cloning cache of Zlib from git://github.com/dcjones/Zlib.jl.git
INFO: Installing BinDeps v0.3.7
INFO: Installing Cairo v0.2.24
INFO: Installing Color v0.4.1
INFO: Installing Compat v0.2.12
INFO: Installing FixedPointNumbers v0.0.6
INFO: Installing Graphics v0.1.0
INFO: Installing IniFile v0.2.4
INFO: Installing LibExpat v0.0.6
INFO: Installing SHA v0.0.3
INFO: Installing Tk v0.2.17
INFO: Installing URIParser v0.0.4
INFO: Installing WinRPM v0.1.6
INFO: Installing Winston v0.11.7
INFO: Installing Zlib v0.1.7
INFO: Building WinRPM
WARNING: skipping repodata/repomd.xml, not in cache -- call WinRPM.update() to download
WARNING: beginswith is deprecated, use startswith instead.
 in depwarn at deprecated.jl:40
 in beginswith at deprecated.jl:10
 in anonymous at C:\Users\SAMSUNG2.julia\v0.4\WinRPM\src\WinRPM.jl:80
 in open at iostream.jl:137
 in getcachedir at C:\Users\SAMSUNG2.julia\v0.4\WinRPM\src\WinRPM.jl:76
 in update at C:\Users\SAMSUNG2.julia\v0.4\WinRPM\src\WinRPM.jl:131
 in **init** at C:\Users\SAMSUNG2.julia\v0.4\WinRPM\src\WinRPM.jl:40
 in include at boot.jl:249
 in include_from_node1 at loading.jl:128
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:51
 in include at boot.jl:249
 in include_from_node1 at loading.jl:128
 in evalfile at loading.jl:168 (repeats 2 times)
 in anonymous at pkg/entry.jl:624
 in cd at file.jl:30
 in build! at pkg/entry.jl:623
 in build! at pkg/entry.jl:619
 in build at pkg/entry.jl:635
 in resolve at pkg/entry.jl:446
 in edit at pkg/entry.jl:24
 in anonymous at task.jl:344
WARNING: split(x,y,l::Integer) is deprecated, use split(x,y; limit=l) instead.
 in depwarn at deprecated.jl:40
 in split at deprecated.jl:29
 in anonymous at C:\Users\SAMSUNG2.julia\v0.4\WinRPM\src\WinRPM.jl:81
 in open at iostream.jl:137
 in getcachedir at C:\Users\SAMSUNG2.julia\v0.4\WinRPM\src\WinRPM.jl:76
 in update at C:\Users\SAMSUNG2.julia\v0.4\WinRPM\src\WinRPM.jl:131
 in __init__ at C:\Users\SAMSUNG2.julia\v0.4\WinRPM\src\WinRPM.jl:40
 in include at boot.jl:249
 in include_from_node1 at loading.jl:128
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:51
 in include at boot.jl:249
 in include_from_node1 at loading.jl:128
 in evalfile at loading.jl:168 (repeats 2 times)
 in anonymous at pkg/entry.jl:624
 in cd at file.jl:30
 in build! at pkg/entry.jl:623
 in build! at pkg/entry.jl:619
 in build at pkg/entry.jl:635
 in resolve at pkg/entry.jl:446
 in edit at pkg/entry.jl:24
 in anonymous at task.jl:344
WARNING: skipping repodata/repomd.xml, not in cache -- call WinRPM.update() to download
WARNING: beginswith is deprecated, use startswith instead.
 in depwarn at deprecated.jl:40
 in beginswith at deprecated.jl:10
 in anonymous at C:\Users\SAMSUNG2.julia\v0.4\WinRPM\src\WinRPM.jl:80
 in open at iostream.jl:137
 in getcachedir at C:\Users\SAMSUNG2.julia\v0.4\WinRPM\src\WinRPM.jl:76
 in update at C:\Users\SAMSUNG2.julia\v0.4\WinRPM\src\WinRPM.jl:131
 in update at C:\Users\SAMSUNG2.julia\v0.4\WinRPM\src\WinRPM.jl:125
 in include at boot.jl:249
 in include_from_node1 at loading.jl:128
 in evalfile at loading.jl:168 (repeats 2 times)
 in anonymous at pkg/entry.jl:624
 in cd at file.jl:30
 in build! at pkg/entry.jl:623
 in build! at pkg/entry.jl:619
 in build at pkg/entry.jl:635
 in resolve at pkg/entry.jl:446
 in edit at pkg/entry.jl:24
 in anonymous at task.jl:344
INFO: Downloading http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.1//repodata/repomd.x
ml
INFO: Downloading http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.1//repodata/3804dc2e
4b633f07095ee8c36ac288bfb544355b763fa8f1fe0254ec716e6f8b-primary.xml.gz
INFO: Downloading http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.1//repodata/repomd.x
ml
INFO: Downloading http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.1//repodata/2b51f3de
32249d7afb94b5da88e64e0ff0e3b92ff3f139c51356dd7d2b70f081-primary.xml.gz
INFO: Building Cairo
WARNING: src::AbstractCmd |> dest::AbstractCmd is deprecated, use pipe(src,dest) instead.
 in depwarn at deprecated.jl:40
 in |> at deprecated.jl:29
 in unpack_cmd at C:\Users\SAMSUNG2.julia\v0.4\BinDeps\src\BinDeps.jl:95
 in lower at C:\Users\SAMSUNG2.julia\v0.4\BinDeps\src\BinDeps.jl:236
 in generate_steps at C:\Users\SAMSUNG2.julia\v0.4\BinDeps\src\dependencies.jl:236
 in lower at C:\Users\SAMSUNG2.julia\v0.4\BinDeps\src\dependencies.jl:254
 in include at boot.jl:249
 in include_from_node1 at loading.jl:128
 in evalfile at loading.jl:168 (repeats 2 times)
 in anonymous at pkg/entry.jl:624
 in cd at file.jl:30
 in build! at pkg/entry.jl:623
 in build at pkg/entry.jl:635
 in resolve at pkg/entry.jl:446
 in edit at pkg/entry.jl:24
 in anonymous at task.jl:344
INFO: Updating WinRPM package list
INFO: Downloading http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.1//repodata/repomd.x
ml
INFO: Downloading http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.1//repodata/repomd.x
ml
INFO: Packages to install: libintl8, libglib-2_0-0, libffi6, glib2-lang, libgobject-2_0-0, glib2
INFO: Downloading: libintl8
INFO: Extracting: libintl8
INFO: Downloading: libglib-2_0-0
INFO: Extracting: libglib-2_0-0
INFO: Downloading: libffi6
INFO: Extracting: libffi6
INFO: Downloading: glib2-lang
INFO: Extracting: glib2-lang
INFO: Downloading: libgobject-2_0-0
INFO: Extracting: libgobject-2_0-0
INFO: Downloading: glib2
INFO: Extracting: glib2
INFO: Complete
INFO: Packages to install: libxml2-2, libfreetype6, libpixman-1-0, zlib1, libgcc_s_seh1, fontconfig, libpng16-16,
libharfbuzz0, libcairo2
INFO: Downloading: libxml2-2
INFO: Extracting: libxml2-2
INFO: Downloading: libfreetype6
INFO: Extracting: libfreetype6
INFO: Downloading: libpixman-1-0
INFO: Extracting: libpixman-1-0
INFO: Downloading: zlib1
INFO: Extracting: zlib1
INFO: Downloading: libgcc_s_seh1
INFO: Extracting: libgcc_s_seh1
INFO: Downloading: fontconfig
INFO: Extracting: fontconfig
INFO: Downloading: libpng16-16
INFO: Extracting: libpng16-16
INFO: Downloading: libharfbuzz0
INFO: Extracting: libharfbuzz0
INFO: Downloading: libcairo2
INFO: Extracting: libcairo2
INFO: Complete
INFO: Packages to install: libgmodule-2_0-0, libpango-1_0-0
INFO: Downloading: libgmodule-2_0-0
INFO: Extracting: libgmodule-2_0-0
INFO: Downloading: libpango-1_0-0
INFO: Extracting: libpango-1_0-0
INFO: Complete
INFO: Building Tk

WARNING: deprecated syntax "[a=>b, ...]" at C:\Users\SAMSUNG2.julia\v0.4\Tk\deps\build.jl:54.
Use "Dict(a=>b, ...)" instead.
INFO: Packages to install: tcl
INFO: Downloading: tcl
INFO: Extracting: tcl
INFO: Complete
INFO: Packages to install: tk
INFO: Downloading: tk
INFO: Extracting: tk
INFO: Complete
INFO: Package database updated

julia> using Winston
ERROR: LoadError: UndefVarError: Graphics not defined
 in include at boot.jl:249
 in include_from_node1 at loading.jl:128
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:51
while loading C:\Users\SAMSUNG2.julia\v0.4\Winston\src\Winston.jl, in expression starting on line 5

julia> WinRPM.update()
INFO: Downloading http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.1//repodata/repomd.x
ml
INFO: Downloading http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.1//repodata/repomd.x
ml

julia> using Winston

julia> plot(rand(10))
ERROR: UndefVarError: plot not defined

julia> In file  :Winston.jl in first lines is :

module Winston

using Cairo
using Color
importall Base.Graphics
using IniFile

export
    closefig,
    colormap,
    errorbar,
...
The dir C:\Users\SAMSUNG2.julia\v0.4 WAS cleanig befor installing.
Winston on this machine works 2 weekes ago :/

Paul

**Comment by timholy** [comment]
Do `Pkg.update()`.

**Comment by paulanalyst** [comment]
Ok, after clean C:/users..., Install, and update() Winston works .
Paul

W dniu 2015-02-25 o 19:51, Tim Holy pisze:

**Comment by paulanalyst** [comment]
Winston works after upadte but on:

Version 0.4.0-dev+3600 (2015-02-25 15:26 UTC)
Commit f96c23c* (0 days old master)
x86_64-w64-mingw32

julia> using Winston
WARNING: [a,b,...] concatenation is deprecated; use [a;b;...] instead
  in depwarn at deprecated.jl:40
  in oldstyle_vcat_warning at abstractarray.jl:26
  in vect at abstractarray.jl:35
  in anonymous at C:\Users\SAMSUNG2\.julia\v0.4\Winston\src\config.jl:6
  in include at boot.jl:249
  in include_from_node1 at loading.jl:128
  in include at boot.jl:249
  in include_from_node1 at loading.jl:128
  in reload_path at loading.jl:152
  in _require at loading.jl:67
  in require at loading.jl:51

Paul

W dniu 2015-02-25 o 19:51, Tim Holy pisze:
