### ISSUE TITLE
Winston segfaulting on latest Julia

### ISSUE THREAD

**Issue by skariel** [nolta/Winston.jl#209]
see image below. Will try to fix, any insights though are appreciated!

![screenshot from 2015-03-16 10 11 22](https://cloud.githubusercontent.com/assets/2347816/6662500/d336412a-cbc4-11e4-8cb3-e12cfd1c2008.png)

**Comment by timholy** [comment]
Tk bug, see https://github.com/timholy/ProfileView.jl/issues/31 which has a link to the crucial information about fixing it.

**Comment by timholy** [comment]
I'm going to close this since it has nothing to do with Winston proper.
