### ISSUE TITLE
Add list of predefined colormaps to docs

### ISSUE THREAD

**Issue by stillyslalom** [nolta/Winston.jl#215]
A list of the [colormaps](https://github.com/JuliaLang/Color.jl#colormaps) defined by Color.jl (or a link to the Color.jl docs) should be included in the Colormaps doc page.

**Comment by slangangular** [comment]
slangangular@979c30a79e79bf505d8874b11e1a09a3df6385b3

**Comment by stillyslalom** [comment]
@slangangular Mind if I create a PR for the various documentation-related commits you've made over the past month?

**Comment by slangangular** [comment]
I'm sorry, I thought I had done that. Here it is: #217
