### ISSUE TITLE
using Winston fails on the first try

### ISSUE THREAD

**Issue by DanielOPerez** [nolta/Winston.jl#216]
Hi everyone!, when I run "using Winston" I get the following (Julia Version 0.4.0-dev+4797 x86_64-linux-gnu)

julia> using Winston
ERROR: LoadError: LoadError: ArgumentError: invalid type for argument rgb in method definition for color_to_rgb at /home/daniel/.julia/v0.4/Winston/src/renderer.jl:64
in include at ./boot.jl:252
in include_from_node1 at ./loading.jl:134
in include at ./boot.jl:252
in include_from_node1 at ./loading.jl:134
in reload_path at ./loading.jl:158
in _require at ./loading.jl:70
in require at ./loading.jl:53
while loading /home/daniel/.julia/v0.4/Winston/src/renderer.jl, in expression starting on line 64
while loading /home/daniel/.julia/v0.4/Winston/src/Winston.jl, in expression starting on line 112

and, of course, I cannot plot anything..Any suggestions or ideas to solve this problem?

Thanks!!!

**Comment by nolta** [comment]
`Pkg.checkout("Winston")` should fix it.

**Comment by DanielOPerez** [comment]
It's working! thank you nolta!!!
