### ISSUE TITLE
ERROR: type cannot be constructed

### ISSUE THREAD

**Issue by LeoK987** [nolta/Winston.jl#219]
Some new updates today broke Winston.  As I have found, the errors relate to Int(b) and Char(digits[1]) in winston.jl.  Changing them to lower case solved the problem.  Do they need to be in cap case in 0.4?

  | | |_| | | | (_| |  |  Version 0.3.8 (2015-04-30 23:40 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org release
|__/                   |  x86_64-linux-gnu

**Comment by heliosdrm** [comment]
Fixed with "@compat" in the master branch
