### ISSUE TITLE
Dates dependency

### ISSUE THREAD

**Issue by my-little-repository** [nolta/Winston.jl#241]
I just reinstalled Winston today. This went fine but when I tried `using Winston`, I got an error complaining that the `Dates` package is not installed. Installing this package solved the problem. I use julia 0.4rc.

**Comment by hustf** [comment]
Same thing with IniFile: https://github.com/JuliaLang/IniFile.jl/issues/13

**Comment by milktrader** [comment]
The Dates package has been put into Base as of version 0.4. To remove the warning, a control flow needs to be put in the front-end of the module.
````julia
if VERSION < v"0.4-"
   using Dates
else
   using Base.Dates
end
````

**Comment by milktrader** [comment]
https://github.com/nolta/Winston.jl/pull/252
