### ISSUE TITLE
Plot() container not working?

### ISSUE THREAD

**Issue by my-little-repository** [nolta/Winston.jl#243]
I am trying to use the Plot() container, as advertised on the wiki, but I get an error.    

    julia> let p = Plot(), x=linspace(-2pi,2pi,100)
               add(p, Curve(x, sin(x)))
               Winston.display(p) 
           end
    ERROR: MethodError: `limits` has no method matching limits(::Winston.Plot)
    Closest candidates are:
      limits(::Winston.Plot, !Matched::Graphics.BoundingBox)
      limits(::Any, !Matched::Any, !Matched::Any, !Matched::Any, !Matched::Any, !Matched::Any)
     in compose_interior at /home/yves/.julia/v0.4/Winston/src/Winston.jl:1447
     in page_compose at /home/yves/.julia/v0.4/Winston/src/Winston.jl:1848
     in page_compose at /home/yves/.julia/v0.4/Winston/src/Winston.jl:1836
     in anonymous at /home/yves/.julia/v0.4/Winston/src/tk.jl:27
     in display at /home/yves/.julia/v0.4/Winston/src/tk.jl:35
     in display at /home/yves/.julia/v0.4/Winston/src/Winston.jl:2855
     [inlined code] from multimedia.jl:151
    
What am I doing wrong?

**Comment by slangangular** [comment]
Try using `FramedPlot()` instead of `Plot()`.

**Comment by my-little-repository** [comment]
I don't want a framed plot. I want a plot without a frame. From the doc, it seems that Plot() is the way to go.

**Comment by slangangular** [comment]
Okay, I'm sorry. Can you try, if bd3c9af0242585137968a77fe5975c4981239763 works for you?

**Comment by my-little-repository** [comment]
@slangangular Yes, it works, thanks.
