### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by iceblue25** [nolta/Winston.jl#245]
Thanks for this wonderful package.

**Comment by tbreloff** [comment]
Can you include the code? Are you plotting lines and markers at the same time?

Also I'm curious. Do you see the same problem if you access Winston through Plots.jl?

**Comment by heliosdrm** [comment]
I could not reproduce that problem.

```julia
plot(randn(6,5))
legend(["one", "two", "three", "four", "five"])
```

shows a legend with the correct color.

So it does:

```julia
plot(randn(6), "k")
hold(true)
plot(randn(6), "r")
plot(randn(6), "b")
plot(randn(6), "g")
plot(randn(6), "y")
legend(["one", "two", "three", "four", "five"])
```

**Comment by slangangular** [comment]
I cannot reproduce this either. It seems to to work fine both in Winston and through the Plots.jl interface.

**Comment by iceblue25** [comment]
Thanks for all the help. It was my bad and a problem with my code. Ignore this issue
