### ISSUE TITLE
Does Winston work with Julia 0.4?

### ISSUE THREAD

**Issue by ealmirall** [nolta/Winston.jl#257]
Hi, 

It looks like Julia doesn't work with 0.4 ... is that true? Such a GREAT package ....!!!!

**Comment by heliosdrm** [comment]
It does. But please specify what's exactly not working for you.

Hint: many experience warnings or errors with the officially registered versions, which have already been fixed in the development version Verify it that's the case by checking out the master branch of Winston and dependent packages (before using them):

    Pkg.checkout("Winston")
    Pkg.checkout("Tk")
    Pkg.checkout("IniFile")

If your problems disappear with that, there should be nothing more to do. You can leave those versions in your system. Or if you don't like having potentially "dirty" versions, go back to the registered ones (same as before, but change "Pkg.checkout" by "Pkg.free"), and wait until future releases.

**Comment by ealmirall** [comment]
Thanks a lot !! 

I am sure that this is the case. How can install the development version ? Really sorry if this sounds too obvious ... :-(

Thanks a lot !!

Esteve Almirall

**Comment by ealmirall** [comment]
Dear Helios, 

I did it … I still get 

julia> using Winston
INFO: Precompiling module Cairo...
ERROR: LoadError: could not open file /Users/ealmirall/.julia/v0.4/Cairo/src/../deps/deps.jl
 in include at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib
 [inlined code] from none:2
 in anonymous at no file:0
 in process_options at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib
 in _start at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib
while loading /Users/ealmirall/.julia/v0.4/Cairo/src/Cairo.jl, in expression starting on line 7
ERROR: LoadError: Failed to precompile Cairo to /Users/ealmirall/.julia/lib/v0.4/Cairo.ji
 in error at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib
 in compilecache at loading.jl:384
 in require at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib
 in require at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib
while loading /Users/ealmirall/.julia/v0.4/Winston/src/Winston.jl, in expression starting on line 3

Thanks a lot !!!!


/ esteve almirall /prof. associat  @ ESADE 
/ Dtr. CIC- Center for Innovation in Cities 
/M esteve.almirall@esade.edu <mailto:esteve.almirall@esade.edu> /S ealmirall /T @ealmirall
/blog estevealmirall.com <http://estevealmirall.com/> /ph+whats +34 609888559

**Comment by ealmirall** [comment]
Really sorry !!!

Stupid of me didn’t agree to the Xcode license … 

Everything works fantastic !!!!

THANKS A LOT !!!!

/ esteve almirall /prof. associat  @ ESADE 
/ Dtr. CIC- Center for Innovation in Cities 
/M esteve.almirall@esade.edu <mailto:esteve.almirall@esade.edu> /S ealmirall /T @ealmirall
/blog estevealmirall.com <http://estevealmirall.com/> /ph+whats +34 609888559

**Comment by ealmirall** [comment]
Dear  Helios,

Sorry to bother you again … 

I am trying to install v0.4 in my iMac and I always get

  _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.2 (2015-12-06 21:47 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-apple-darwin13.4.0

julia> using Winston
INFO: Recompiling stale cache file /Users/ea/.julia/lib/v0.4/Cairo.ji for module Cairo.
WARNING: requiring "Dates" in module "Winston" did not define a corresponding module.
WARNING: module Winston should explicitly import * from Base
ERROR: LoadError: LoadError: LoadError: LoadError: UndefVarError: _jl_libgobject not defined
 in init at /Users/ea/.julia/v0.4/Tk/src/tkwidget.jl:36
 in include at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib
 in require at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib
 in require at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib
while loading /Users/ea/.julia/v0.4/Tk/src/tkwidget.jl, in expression starting on line 454
while loading /Users/ea/.julia/v0.4/Tk/src/Tk.jl, in expression starting on line 37
while loading /Users/ea/.julia/v0.4/Winston/src/tk.jl, in expression starting on line 1
while loading /Users/ea/.julia/v0.4/Winston/src/Winston.jl, in expression starting on line 2842

I do a clean installation. I delete .julia and .julia_history and also julia in the Applications folder (I use a Mac). I download and install. Should I delete something else?

I have X11 installed (Quartz).

Thanks a lot !!!

esteve almirall
