### ISSUE TITLE
WARNING: [a,b] concatenation is deprecated; use [a;b] instead

### ISSUE THREAD

**Issue by jmarcellopereira** [nolta/Winston.jl#259]
how to solve?

code:
x = [0.0 1.0      1.5      2.0       2.5      3.0        3.5        4.0       4.5        5.0        5.5000     6.0       6.5        7.0       7.5       8.0       8.5       9.0        9.5        10.0];
y = [0.0 0.841471 0.997495 0.909297  0.598472 0.141120  -0.350783  -0.756802 -0.977530  -0.958924  -0.705540  -0.279415  0.215120   0.656987  0.938000  0.989358  0.798487  0.412118  -0.075151  -0.544021];

using Winston

Winston.plot(x,y,"or")

I use also Gadfly in notebook

**Comment by kmsquire** [comment]
Seems to be fixed on master.
