### ISSUE TITLE
deproject method overwritten

### ISSUE THREAD

**Issue by kilminster** [nolta/Winston.jl#262]
at line 85 in geom.jl:
`deproject(p::LinearProjection, x) = 10.0 .^ ((x .- p.a) ./ p.b)`

I'm guessing this should be:
`deproject(p::LogProjection, x) = 10.0 .^ ((x .- p.a) ./ p.b)`

**Comment by JeffBezanson** [comment]
Fixed by 4a6f607866057ebc7d5d01c3d00fc4d746bde578
