### ISSUE TITLE
savefig() not working for tables

### ISSUE THREAD

**Issue by nickmoore83** [nolta/Winston.jl#265]
Hi, I very much enjoy using Winston to make plots in Julia. I came across an issue when attempting to save a table comprised of two plots to a file. Here, savefig() does not save the table, but only the most recent plot. An example is below.

using Winston
xx = collect(0.0:0.1:1.0)
p1 = plot(xx,xx.^2)
p2 = plot(xx,xx.^3)
tbl = Table(1,2)
tbl[1,1] = p1
tbl[1,2] = p2
figure()
display(tbl)
savefig("fig1.png")

**Comment by heliosdrm** [comment]
Hi Nick. Just tell `savefig` what object do you actually want to print into the file:

```
savefig(tbl, "fig1.png")
```

**Comment by nickmoore83** [comment]
ahh, thank you!
