### ISSUE TITLE
How to solve :WARNING: deprecated syntax "AbstractVecOrMat{T} ?

### ISSUE THREAD

**Issue by jmarcellopereira** [nolta/Winston.jl#267]
Winston.plot(x -> sin(x)*x,0,2) Winston.grid() using Winston ​ Winston.plot(x -> sin(x)*x,0,2) Winston.grid()

WARNING: deprecated syntax "AbstractVecOrMat{T} (" at /home/jmarcellopereira/.julia/v0.4/Winston/src/Winston.jl:96. Use "AbstractVecOrMat{T}(" instead. WARNING: requiring "Dates" in module "Winston" did not define a corresponding module. WARNING: module Winston should explicitly import * from Base WARNING: both Winston and SymPy export "Curve"; uses of it in module Main must be qualified

**Comment by JeffBezanson** [comment]
Fixed on master.
