### ISSUE TITLE
Fails on `Julia 0.5`

### ISSUE THREAD

**Issue by abhijithch** [nolta/Winston.jl#270]
On `julia v0.5`, I get the following error,
`ERROR: LoadError: syntax: space before "(" not allowed in "AbstractVecOrMat{T}`. By removing the space it works fine on `julia v0.5` and also removes a depwarn in `julia v0.4`. I can send a PR if minimum version for `julia` is pinned to `v0.4`, which is `v0.2` right now.

**Comment by jonathanBieler** [comment]
That would be nice, this is also causing troubles in other packages.

**Comment by abhijithch** [comment]
This is fixed in 6dd2496, this badly needs a tag. Closing this issue.
